### ISSUE TITLE
Launcing sh.fxf from Fetcher corrupts the boot disk

### ISSUE THREAD

**Issue by mebibytedraco** [fox32-arch/fox32os#17]
Clicking on sh.fxf in Fetcher causes the OS to become unresponsive (though the mouse cursor still moves), and the boot disk image to increase in file size by about 10 MB. Attempting to restart the emulator using the corrupted image results in the "missing disk" icon upon boot.

**Comment by ry755** [comment]
I actually ran into this exact issue last night after first getting Fetcher to launch FXF binaries. I haven't looked into it yet but my theory on why this happens is because sh.fxf expects a stream struct to be passed to it. terminal.fxf passes its stream struct (used for sending characters to/from the terminal) to sh.fxf when it starts it, but Fetcher just passes a null pointer. sh.fxf doesn't check for a null pointer before attempting to use the stream struct, so it dereferences it (fox32os runs without the MMU enabled, so derefing a null pointer is technically allowed) and sees all zeros, which fox32os's `write` routine interprets as a *file* struct instead of a stream struct. This results in sh.fxf writing to what it thinks is a file on disk 0, starting at sector 0, with seek offset 0, aka the raw disk lol.

Also the fact that it increases the disk image size seems like a separate bug in the emulator itself. It shouldn't be possible/allowed for writes past the end of the disk to go through and append to the disk image.

**Comment by ry755** [comment]
And in fact, it looks like that's what's happening! I launched sh.fxf from Fetcher, entered the ROM monitor by pressing F12, then loaded sector 0 of disk 0 into memory at 0x800, then listed the contents of memory at that address. Circled in red is the shell prompt (which is weirdly missing the disk number that would normally be at the shell prompt?), and underlined in green is 0xFE three times, which is the terminal control command to redraw the line. After that it seems like sh.fxf maybe starts receiving the raw bytes from disk 0 due to the invalid stream struct explained in the above post? Not sure.

![Screenshot from 2023-07-13 20-44-58](https://github.com/fox32-arch/fox32os/assets/23299242/04bc722b-2f31-4919-83f5-7e229ac51756)

**Comment by ry755** [comment]
Fixed in 0059493bb209d6aa8a769669dcf9582eea052d5c.
