### ISSUE TITLE
Clicking "<empty>" icon in Fetcher crashes system with jump to null pointer

### ISSUE THREAD

**Issue by ry755** [fox32-arch/fox32os#18]
The register dump shows r0 as 0xFFFFFFFF, which maybe implies that's what `launch_fxf_from_disk` is returning? Not sure, will need more investigation.

**Comment by mebibytedraco** [comment]
I did some testing and discovered that the system crashes whenever launch_fxf_from_disk is passed an invalid filename. After ruling out any jumps performed inside the routine, I decided to count the pushes and pops from the stack to make sure they were balanced. Turns out launch_fxf_from_disk pushes an extra copy of the program parameters onto the stack, which weren't removed when an error occured, so the CPU jumps to the address specified by the saved contents of r5. PR #19 should fix this.
