### ISSUE TITLE
Please add description in readme.md

### ISSUE THREAD

**Issue by sashaindrish** [fox32-arch/fox32os#2]
## How Use
...

And why don't use QEMU, in your VM?

**Comment by ry755** [comment]
So, currently the steps for building fox32os yourself are a bit complicated. I'll try my best to explain them here, then in the future I'll take these instructions and try to condense them down to put into the readme.
Also feel free to join the [fox32 Discord server](https://discord.gg/2Tun7FnUZ2) for further help :3

First, set up the Rust toolchain by following the instructions [here](https://www.rust-lang.org/learn/get-started). You'll need this in order to build fox32asm and gfx2inc.

Currently the process includes cloning multiple repositories, all of which are available [here](https://github.com/fox32-arch).
You want the directory structure to look something like this:
 - project_root/
     - fox32asm/
         - src/
         - ...
     - fox32rom/
         - main.asm
         - ...
     - fox32os/
         - main.asm
         - ...
     - tools/
         - gfx2inc/
         - ...

Then, `cd` into the `fox32asm/` folder and run `cargo build --release`.
Then, `cd` back to the project root, then `cd` into `tools/gfx2inc/` and run `cargo build --release`.

Finally, `cd` into the fox32os/ folder and run the `build.sh` script. This will create a disk image called fox32os.img, which can be run with [fox32](https://github.com/fox32-arch/fox32).

Hopefully these instructions make sense, let me know if you need further help :3

> And why don't use QEMU, in your VM?

Mostly because I don't know how QEMU works internally, and creating my own little VM was the easiest option :P

**Comment by ry755** [comment]
Now that the build system has been overhauled to use `make`, I think this can be closed now.
