### ISSUE TITLE
Weirdness with Fetcher when no other windows are open

### ISSUE THREAD

**Issue by ry755** [fox32-arch/fox32os#22]
Fetcher acts weirdly when no other windows are open. The first part of the video shows what happens when a Fetcher window is open and then all other windows are closed afterwards, and the second part of the video shows what happens when a Fetcher window is attempted to be opened after all other windows are closed. This seems to be related to commit 1f025dd55ed44e6ff9c143fe9a76d39c241cab49, this bug does not occur on builds before this commit. But after briefly looking through the code I'm not sure *why* this commit causes this bug.

https://github.com/fox32-arch/fox32os/assets/23299242/badc56a9-21c6-46e8-94e9-e174b4592f3c

**Comment by mebibytedraco** [comment]
Just started investigating. It looks like it happens whenever the Launcher window is closed, regardless of how many other windows are open. I think it might be some side effect of the Launcher being the first application to have a non-background window when the system is started. Going to continue testing.

**Comment by mebibytedraco** [comment]
Found the issue! 1f025dd reorganized destroy_window so that the selection of the new active window occurs before the window that is about to be destroyed is removed from the window list. As a result, when the Launcher window is closed, it attempts to set itself as the new active window, right before it is destroyed (oops). Currently working on a patch to fix this.
